### ISSUE TITLE
Better filenames for Java samples

### ISSUE THREAD

**Issue by johannesl** [46elks/46elks-getting-started#11]
Make it clearer that the samples are the same for plain Java and Unirest. Maybe like this:

SendSMS.java
SendSMS-Unirest.java
SendSMS-HttpClient.java (to be added)

**Comment by johannesl** [comment]
Here's a link for building the HttpClient sample:
https://hc.apache.org/httpcomponents-client-ga/tutorial/html/fluent.html

**Comment by themaxsandelin** [comment]
@johannesl Renamed the files in pull request #25.

You should open a separate issue for creating the HttpClient sample and include hashtags so others can come in and contribute. 👍
