### ISSUE TITLE
Need a GitHub Action

### ISSUE THREAD

**Issue by mikaeldui** [46elks/46elks-getting-started#27]
Why is there no GitHub Action available for 46elks? It'd be really nice to send an SMS on build success/fail or when there's a new PR to review etc.

**Comment by reinefjord** [comment]
Thank you for the suggestion, that does sound like a great way to use our API! I'll look into creating one.

**Comment by reinefjord** [comment]
I've just uploaded https://github.com/46elks/gh-actions-sms, would you mind trying it out and reporting back whether it works for you? :)

**Comment by mikaeldui** [comment]
It's working fine, thanks! :)

**Comment by mikaeldui** [comment]
@reinefjord could you have a look at the related issue https://github.com/46elks/gh-actions-sms/issues/1 ?
